### ISSUE TITLE
Linux - use more current version of node

### ISSUE THREAD

**Issue by dpickett** [LaunchAcademy/rocket-fuel-chef#16]
Node is horribly out of date via apt-get

**Comment by SpencerCDixon** [comment]
can't you just curl nvm and use that? https://github.com/creationix/nvm#install-script

**Comment by dpickett** [comment]
:+1: thanks @SpencerCDixon. I spent the entire, damn morning trying to find a decent cookbook/recipe for this, but I ultimately just ended up scripting directly with nvm. If you're curious, the recipe is at https://github.com/LaunchAcademy/rocket-fuel-chef/blob/master/la_cookbooks/fueled-linux-apps/recipes/node.rb

**Comment by SpencerCDixon** [comment]
yup already saw it! looks good
