### ISSUE TITLE
Entering apple credentials

### ISSUE THREAD

**Issue by HeroicEric** [LaunchAcademy/rocket-fuel-chef#3]
I know that I wouldn't enter my Apple credentials into a script from the internet and I'm not sure we should encourage others to do so. We might be able to get away with this internally, as I think people attending would trust us, but to get anybody outside of launch to use it, this might turn them away.

 I think we should investigate some other options.

A few that I can think of:

* Just link them to the Apple website as a prereq before running the script and download the command line tools manually
* Maybe we can find another source or host our own?

**Comment by dpickett** [comment]
the command line script is now defunct and `xcode-select --install` works more reliably now.
